// Generated by Progenitor 0.14.0. Do not edit.
#[allow(unused_imports)]
pub use progenitor_client::{ByteStream, ClientInfo, Error, ResponseValue};
#[allow(unused_imports)]
use progenitor_client::{encode_path, ClientHooks, OperationInfo, RequestBuilderExt};
/// Types used as operation parameters and responses.
#[allow(clippy::all)]
pub mod types {
    fn deserialize_required_nullable<'de, D>(
        deserializer: D,
    ) -> ::std::result::Result<::std::option::Option<::std::string::String>, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        <::std::option::Option<::std::string::String> as ::serde::Deserialize>::deserialize(deserializer)
    }
    fn deserialize_nonnegative_int32<'de, D>(deserializer: D) -> ::std::result::Result<i32, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        let value = <i32 as ::serde::Deserialize>::deserialize(deserializer)?;
        if value < 0 {
            return Err(<D::Error as ::serde::de::Error>::custom("integer must be nonnegative"));
        }
        Ok(value)
    }
    fn deserialize_utc_datetime<'de, D>(
        deserializer: D,
    ) -> ::std::result::Result<::chrono::DateTime<::chrono::offset::Utc>, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        let value = <::std::string::String as ::serde::Deserialize>::deserialize(deserializer)?;
        if !value.ends_with('Z') {
            return Err(<D::Error as ::serde::de::Error>::custom("date-time must use the UTC Z suffix"));
        }
        value.parse().map_err(<D::Error as ::serde::de::Error>::custom)
    }
    /// Error types.
    pub mod error {
        /// Error from a `TryFrom` or `FromStr` implementation.
        pub struct ConversionError(::std::borrow::Cow<'static, str>);
        impl ::std::error::Error for ConversionError {}
        impl ::std::fmt::Display for ConversionError {
            fn fmt(
                &self,
                f: &mut ::std::fmt::Formatter<'_>,
            ) -> Result<(), ::std::fmt::Error> {
                ::std::fmt::Display::fmt(&self.0, f)
            }
        }
        impl ::std::fmt::Debug for ConversionError {
            fn fmt(
                &self,
                f: &mut ::std::fmt::Formatter<'_>,
            ) -> Result<(), ::std::fmt::Error> {
                ::std::fmt::Debug::fmt(&self.0, f)
            }
        }
        impl From<&'static str> for ConversionError {
            fn from(value: &'static str) -> Self {
                Self(value.into())
            }
        }
        impl From<String> for ConversionError {
            fn from(value: String) -> Self {
                Self(value.into())
            }
        }
    }
    ///`ContractProof`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "object",
    ///  "required": [
    ///    "count",
    ///    "event",
    ///    "occurredAt",
    ///    "requiredNullable"
    ///  ],
    ///  "properties": {
    ///    "count": {
    ///      "type": "integer",
    ///      "format": "int32",
    ///      "maximum": 2147483647.0,
    ///      "minimum": 0.0
    ///    },
    ///    "event": {
    ///      "$ref": "#/components/schemas/ContractProofEvent"
    ///    },
    ///    "occurredAt": {
    ///      "type": "string",
    ///      "format": "date-time",
    ///      "pattern": "Z$"
    ///    },
    ///    "optionalValue": {
    ///      "type": "string"
    ///    },
    ///    "requiredNullable": {
    ///      "type": [
    ///        "string",
    ///        "null"
    ///      ]
    ///    }
    ///  },
    ///  "additionalProperties": false
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    #[serde(deny_unknown_fields)]
    pub struct ContractProof {
        #[serde(deserialize_with = "deserialize_nonnegative_int32")]
        pub count: i32,
        pub event: ContractProofEvent,
        #[serde(
            rename = "occurredAt",
            deserialize_with = "deserialize_utc_datetime"
        )]
        pub occurred_at: ::chrono::DateTime<::chrono::offset::Utc>,
        #[serde(
            rename = "optionalValue",
            default,
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub optional_value: ::std::option::Option<::std::string::String>,
        #[serde(
            rename = "requiredNullable",
            deserialize_with = "deserialize_required_nullable"
        )]
        pub required_nullable: ::std::option::Option<::std::string::String>,
    }
    ///`ContractProofEvent`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "oneOf": [
    ///    {
    ///      "type": "object",
    ///      "required": [
    ///        "attempt",
    ///        "kind"
    ///      ],
    ///      "properties": {
    ///        "attempt": {
    ///          "type": "integer",
    ///          "format": "int32",
    ///          "maximum": 2147483647.0,
    ///          "minimum": 0.0
    ///        },
    ///        "kind": {
    ///          "type": "string",
    ///          "enum": [
    ///            "ready"
    ///          ]
    ///        }
    ///      },
    ///      "additionalProperties": false
    ///    },
    ///    {
    ///      "type": "object",
    ///      "required": [
    ///        "kind",
    ///        "message"
    ///      ],
    ///      "properties": {
    ///        "kind": {
    ///          "type": "string",
    ///          "enum": [
    ///            "failed"
    ///          ]
    ///        },
    ///        "message": {
    ///          "type": "string",
    ///          "minLength": 1
    ///        }
    ///      },
    ///      "additionalProperties": false
    ///    }
    ///  ]
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    #[serde(tag = "kind", deny_unknown_fields)]
    pub enum ContractProofEvent {
        #[serde(rename = "ready")]
        Ready {
            #[serde(deserialize_with = "deserialize_nonnegative_int32")]
            attempt: i32,
        },
        #[serde(rename = "failed")]
        Failed { message: ContractProofEventMessage },
    }
    ///`ContractProofEventMessage`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "string",
    ///  "minLength": 1
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
    #[serde(transparent)]
    pub struct ContractProofEventMessage(::std::string::String);
    impl ::std::ops::Deref for ContractProofEventMessage {
        type Target = ::std::string::String;
        fn deref(&self) -> &::std::string::String {
            &self.0
        }
    }
    impl ::std::convert::From<ContractProofEventMessage> for ::std::string::String {
        fn from(value: ContractProofEventMessage) -> Self {
            value.0
        }
    }
    impl ::std::str::FromStr for ContractProofEventMessage {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            if value.chars().count() < 1usize {
                return Err("shorter than 1 characters".into());
            }
            Ok(Self(value.to_string()))
        }
    }
    impl ::std::convert::TryFrom<&str> for ContractProofEventMessage {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String> for ContractProofEventMessage {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for ContractProofEventMessage {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl<'de> ::serde::Deserialize<'de> for ContractProofEventMessage {
        fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
        where
            D: ::serde::Deserializer<'de>,
        {
            ::std::string::String::deserialize(deserializer)?
                .parse()
                .map_err(|e: self::error::ConversionError| {
                    <D::Error as ::serde::de::Error>::custom(e.to_string())
                })
        }
    }
    ///`GetContractProofXInternalSecret`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "string",
    ///  "minLength": 1
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
    #[serde(transparent)]
    pub struct GetContractProofXInternalSecret(::std::string::String);
    impl ::std::ops::Deref for GetContractProofXInternalSecret {
        type Target = ::std::string::String;
        fn deref(&self) -> &::std::string::String {
            &self.0
        }
    }
    impl ::std::convert::From<GetContractProofXInternalSecret>
    for ::std::string::String {
        fn from(value: GetContractProofXInternalSecret) -> Self {
            value.0
        }
    }
    impl ::std::str::FromStr for GetContractProofXInternalSecret {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            if value.chars().count() < 1usize {
                return Err("shorter than 1 characters".into());
            }
            Ok(Self(value.to_string()))
        }
    }
    impl ::std::convert::TryFrom<&str> for GetContractProofXInternalSecret {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String>
    for GetContractProofXInternalSecret {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String>
    for GetContractProofXInternalSecret {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl<'de> ::serde::Deserialize<'de> for GetContractProofXInternalSecret {
        fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
        where
            D: ::serde::Deserializer<'de>,
        {
            ::std::string::String::deserialize(deserializer)?
                .parse()
                .map_err(|e: self::error::ConversionError| {
                    <D::Error as ::serde::de::Error>::custom(e.to_string())
                })
        }
    }
    ///`PlayerRefreshResponse`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "object",
    ///  "required": [
    ///    "player",
    ///    "refresh"
    ///  ],
    ///  "properties": {
    ///    "player": {
    ///      "type": [
    ///        "object",
    ///        "null"
    ///      ],
    ///      "required": [
    ///        "brawlhallaId",
    ///        "name"
    ///      ],
    ///      "properties": {
    ///        "brawlhallaId": {
    ///          "type": "integer",
    ///          "maximum": 2147483647.0,
    ///          "exclusiveMinimum": 0.0
    ///        },
    ///        "name": {
    ///          "type": "string"
    ///        }
    ///      },
    ///      "additionalProperties": false
    ///    },
    ///    "refresh": {
    ///      "$ref": "#/components/schemas/RefreshOutcome"
    ///    }
    ///  },
    ///  "additionalProperties": false
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    #[serde(deny_unknown_fields)]
    pub struct PlayerRefreshResponse {
        pub player: ::std::option::Option<PlayerRefreshResponsePlayer>,
        pub refresh: RefreshOutcome,
    }
    ///`PlayerRefreshResponsePlayer`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "object",
    ///  "required": [
    ///    "brawlhallaId",
    ///    "name"
    ///  ],
    ///  "properties": {
    ///    "brawlhallaId": {
    ///      "type": "integer",
    ///      "maximum": 2147483647.0,
    ///      "exclusiveMinimum": 0.0
    ///    },
    ///    "name": {
    ///      "type": "string"
    ///    }
    ///  },
    ///  "additionalProperties": false
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    #[serde(deny_unknown_fields)]
    pub struct PlayerRefreshResponsePlayer {
        #[serde(rename = "brawlhallaId")]
        pub brawlhalla_id: ::std::num::NonZeroU64,
        pub name: ::std::string::String,
    }
    ///`RefreshNoRetryGuidance`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "object",
    ///  "required": [
    ///    "kind"
    ///  ],
    ///  "properties": {
    ///    "kind": {
    ///      "type": "string",
    ///      "enum": [
    ///        "none"
    ///      ]
    ///    }
    ///  },
    ///  "additionalProperties": false
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    #[serde(deny_unknown_fields)]
    pub struct RefreshNoRetryGuidance {
        pub kind: RefreshNoRetryGuidanceKind,
    }
    ///`RefreshNoRetryGuidanceKind`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "string",
    ///  "enum": [
    ///    "none"
    ///  ]
    ///}
    /// ```
    /// </details>
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum RefreshNoRetryGuidanceKind {
        #[serde(rename = "none")]
        None,
    }
    impl ::std::fmt::Display for RefreshNoRetryGuidanceKind {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::None => f.write_str("none"),
            }
        }
    }
    impl ::std::str::FromStr for RefreshNoRetryGuidanceKind {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "none" => Ok(Self::None),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for RefreshNoRetryGuidanceKind {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String> for RefreshNoRetryGuidanceKind {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for RefreshNoRetryGuidanceKind {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`RefreshOutcome`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "oneOf": [
    ///    {
    ///      "type": "object",
    ///      "required": [
    ///        "operationId",
    ///        "outcome",
    ///        "retry"
    ///      ],
    ///      "properties": {
    ///        "operationId": {
    ///          "type": "string",
    ///          "format": "uuid"
    ///        },
    ///        "outcome": {
    ///          "type": "string",
    ///          "enum": [
    ///            "accepted"
    ///          ]
    ///        },
    ///        "retry": {
    ///          "$ref": "#/components/schemas/RefreshPollGuidance"
    ///        }
    ///      },
    ///      "additionalProperties": false
    ///    },
    ///    {
    ///      "type": "object",
    ///      "required": [
    ///        "operationId",
    ///        "outcome",
    ///        "retry"
    ///      ],
    ///      "properties": {
    ///        "operationId": {
    ///          "type": "string",
    ///          "format": "uuid"
    ///        },
    ///        "outcome": {
    ///          "type": "string",
    ///          "enum": [
    ///            "alreadyRefreshing"
    ///          ]
    ///        },
    ///        "retry": {
    ///          "$ref": "#/components/schemas/RefreshPollGuidance"
    ///        }
    ///      },
    ///      "additionalProperties": false
    ///    },
    ///    {
    ///      "type": "object",
    ///      "required": [
    ///        "outcome",
    ///        "retry"
    ///      ],
    ///      "properties": {
    ///        "outcome": {
    ///          "type": "string",
    ///          "enum": [
    ///            "notNeeded"
    ///          ]
    ///        },
    ///        "retry": {
    ///          "$ref": "#/components/schemas/RefreshNoRetryGuidance"
    ///        }
    ///      },
    ///      "additionalProperties": false
    ///    },
    ///    {
    ///      "type": "object",
    ///      "required": [
    ///        "outcome",
    ///        "retry"
    ///      ],
    ///      "properties": {
    ///        "outcome": {
    ///          "type": "string",
    ///          "enum": [
    ///            "verificationRequired"
    ///          ]
    ///        },
    ///        "retry": {
    ///          "$ref": "#/components/schemas/RefreshVerifyGuidance"
    ///        }
    ///      },
    ///      "additionalProperties": false
    ///    },
    ///    {
    ///      "type": "object",
    ///      "required": [
    ///        "outcome",
    ///        "retry"
    ///      ],
    ///      "properties": {
    ///        "outcome": {
    ///          "type": "string",
    ///          "enum": [
    ///            "rateLimited"
    ///          ]
    ///        },
    ///        "retry": {
    ///          "$ref": "#/components/schemas/RefreshRetryAfterGuidance"
    ///        }
    ///      },
    ///      "additionalProperties": false
    ///    },
    ///    {
    ///      "type": "object",
    ///      "required": [
    ///        "outcome",
    ///        "retry"
    ///      ],
    ///      "properties": {
    ///        "outcome": {
    ///          "type": "string",
    ///          "enum": [
    ///            "temporarilyUnavailable"
    ///          ]
    ///        },
    ///        "retry": {
    ///          "$ref": "#/components/schemas/RefreshRetryAfterGuidance"
    ///        }
    ///      },
    ///      "additionalProperties": false
    ///    }
    ///  ]
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    #[serde(tag = "outcome", deny_unknown_fields)]
    pub enum RefreshOutcome {
        #[serde(rename = "accepted")]
        Accepted {
            #[serde(rename = "operationId")]
            operation_id: ::uuid::Uuid,
            retry: RefreshPollGuidance,
        },
        #[serde(rename = "alreadyRefreshing")]
        AlreadyRefreshing {
            #[serde(rename = "operationId")]
            operation_id: ::uuid::Uuid,
            retry: RefreshPollGuidance,
        },
        #[serde(rename = "notNeeded")]
        NotNeeded { retry: RefreshNoRetryGuidance },
        #[serde(rename = "verificationRequired")]
        VerificationRequired { retry: RefreshVerifyGuidance },
        #[serde(rename = "rateLimited")]
        RateLimited { retry: RefreshRetryAfterGuidance },
        #[serde(rename = "temporarilyUnavailable")]
        TemporarilyUnavailable { retry: RefreshRetryAfterGuidance },
    }
    ///`RefreshPollGuidance`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "object",
    ///  "required": [
    ///    "afterSeconds",
    ///    "kind"
    ///  ],
    ///  "properties": {
    ///    "afterSeconds": {
    ///      "type": "integer",
    ///      "format": "int32",
    ///      "maximum": 86400.0,
    ///      "minimum": 1.0
    ///    },
    ///    "kind": {
    ///      "type": "string",
    ///      "enum": [
    ///        "poll"
    ///      ]
    ///    }
    ///  },
    ///  "additionalProperties": false
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    #[serde(deny_unknown_fields)]
    pub struct RefreshPollGuidance {
        #[serde(rename = "afterSeconds")]
        pub after_seconds: ::std::num::NonZeroU32,
        pub kind: RefreshPollGuidanceKind,
    }
    ///`RefreshPollGuidanceKind`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "string",
    ///  "enum": [
    ///    "poll"
    ///  ]
    ///}
    /// ```
    /// </details>
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum RefreshPollGuidanceKind {
        #[serde(rename = "poll")]
        Poll,
    }
    impl ::std::fmt::Display for RefreshPollGuidanceKind {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Poll => f.write_str("poll"),
            }
        }
    }
    impl ::std::str::FromStr for RefreshPollGuidanceKind {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "poll" => Ok(Self::Poll),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for RefreshPollGuidanceKind {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String> for RefreshPollGuidanceKind {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for RefreshPollGuidanceKind {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`RefreshRetryAfterGuidance`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "object",
    ///  "required": [
    ///    "afterSeconds",
    ///    "kind"
    ///  ],
    ///  "properties": {
    ///    "afterSeconds": {
    ///      "type": "integer",
    ///      "format": "int32",
    ///      "maximum": 86400.0,
    ///      "minimum": 1.0
    ///    },
    ///    "kind": {
    ///      "type": "string",
    ///      "enum": [
    ///        "after"
    ///      ]
    ///    }
    ///  },
    ///  "additionalProperties": false
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    #[serde(deny_unknown_fields)]
    pub struct RefreshRetryAfterGuidance {
        #[serde(rename = "afterSeconds")]
        pub after_seconds: ::std::num::NonZeroU32,
        pub kind: RefreshRetryAfterGuidanceKind,
    }
    ///`RefreshRetryAfterGuidanceKind`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "string",
    ///  "enum": [
    ///    "after"
    ///  ]
    ///}
    /// ```
    /// </details>
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum RefreshRetryAfterGuidanceKind {
        #[serde(rename = "after")]
        After,
    }
    impl ::std::fmt::Display for RefreshRetryAfterGuidanceKind {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::After => f.write_str("after"),
            }
        }
    }
    impl ::std::str::FromStr for RefreshRetryAfterGuidanceKind {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "after" => Ok(Self::After),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for RefreshRetryAfterGuidanceKind {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String>
    for RefreshRetryAfterGuidanceKind {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String>
    for RefreshRetryAfterGuidanceKind {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`RefreshVerifyGuidance`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "object",
    ///  "required": [
    ///    "kind"
    ///  ],
    ///  "properties": {
    ///    "kind": {
    ///      "type": "string",
    ///      "enum": [
    ///        "verify"
    ///      ]
    ///    }
    ///  },
    ///  "additionalProperties": false
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    #[serde(deny_unknown_fields)]
    pub struct RefreshVerifyGuidance {
        pub kind: RefreshVerifyGuidanceKind,
    }
    ///`RefreshVerifyGuidanceKind`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "string",
    ///  "enum": [
    ///    "verify"
    ///  ]
    ///}
    /// ```
    /// </details>
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum RefreshVerifyGuidanceKind {
        #[serde(rename = "verify")]
        Verify,
    }
    impl ::std::fmt::Display for RefreshVerifyGuidanceKind {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Verify => f.write_str("verify"),
            }
        }
    }
    impl ::std::str::FromStr for RefreshVerifyGuidanceKind {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "verify" => Ok(Self::Verify),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for RefreshVerifyGuidanceKind {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String> for RefreshVerifyGuidanceKind {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for RefreshVerifyGuidanceKind {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
}
#[derive(Clone, Debug)]
/**Client for BrawlTome Internal Contracts

Version: 1.0.0*/
pub struct Client {
    pub(crate) baseurl: String,
    pub(crate) client: reqwest::Client,
}
impl Client {
    /// Create a new client.
    ///
    /// `baseurl` is the base URL provided to the internal
    /// `reqwest::Client`, and should include a scheme and hostname,
    /// as well as port and a path stem if applicable.
    pub fn new(baseurl: &str) -> Self {
        #[cfg(not(target_arch = "wasm32"))]
        let client = {
            let dur = ::std::time::Duration::from_secs(15u64);
            reqwest::ClientBuilder::new().connect_timeout(dur).timeout(dur)
        };
        #[cfg(target_arch = "wasm32")]
        let client = reqwest::ClientBuilder::new();
        Self::new_with_client(baseurl, client.build().unwrap())
    }
    /// Construct a new client with an existing `reqwest::Client`,
    /// allowing more control over its configuration.
    ///
    /// `baseurl` is the base URL provided to the internal
    /// `reqwest::Client`, and should include a scheme and hostname,
    /// as well as port and a path stem if applicable.
    pub fn new_with_client(baseurl: &str, client: reqwest::Client) -> Self {
        Self {
            baseurl: baseurl.to_string(),
            client,
        }
    }
}
impl ClientInfo<()> for Client {
    fn api_version() -> &'static str {
        "1.0.0"
    }
    fn baseurl(&self) -> &str {
        self.baseurl.as_str()
    }
    fn client(&self) -> &reqwest::Client {
        &self.client
    }
    fn inner(&self) -> &() {
        &()
    }
}
impl ClientHooks<()> for &Client {}
#[allow(clippy::all)]
impl Client {
    /**Sends a `GET` request to `/internal/contracts/proof`

*/
    pub async fn get_contract_proof<'a>(
        &'a self,
        x_internal_secret: &'a types::GetContractProofXInternalSecret,
    ) -> Result<ResponseValue<types::ContractProof>, Error<()>> {
        let url = format!("{}/internal/contracts/proof", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(2usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        header_map
            .append("x-internal-secret", x_internal_secret.to_string().try_into()?);
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "get_contract_proof",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
}
/// Items consumers will typically use such as the Client.
pub mod prelude {
    #[allow(unused_imports)]
    pub use super::Client;
}
