use std::{env, fs, path::PathBuf};

fn main() {
    let package_root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..");
    let spec_path = package_root.join("openapi/contract-proof.openapi.json");
    let output_path = package_root.join("rust/src/generated.rs");

    let spec =
        serde_json::from_slice(&fs::read(spec_path).expect("read committed OpenAPI document"))
            .expect("parse OpenAPI document");
    let tokens = progenitor::Generator::default()
        .generate_tokens(&spec)
        .expect("generate Progenitor client");
    let syntax = syn::parse2(tokens).expect("parse generated Rust");
    let source = enforce_wire_semantics(format!(
        "// Generated by Progenitor 0.14.0. Do not edit.\n{}",
        prettyplease::unparse(&syntax)
    ));

    fs::write(output_path, source).expect("write generated Rust client");
}

fn enforce_wire_semantics(source: String) -> String {
    let nullable_field = "        #[serde(rename = \"requiredNullable\")]\n        pub required_nullable: ::std::option::Option<::std::string::String>,";
    let count_field = "        pub count: i32,";
    let attempt_field = "        Ready { attempt: i32 },";
    let date_time_field = "        #[serde(rename = \"occurredAt\")]\n        pub occurred_at: ::chrono::DateTime<::chrono::offset::Utc>,";
    assert!(
        source.contains(nullable_field),
        "Progenitor required-nullable mapping changed"
    );
    assert!(
        source.contains(count_field),
        "Progenitor bounded count mapping changed"
    );
    assert!(
        source.contains(attempt_field),
        "Progenitor bounded attempt mapping changed"
    );
    assert!(
        source.contains(date_time_field),
        "Progenitor date-time mapping changed"
    );

    let helpers = r#"    fn deserialize_required_nullable<'de, D>(
        deserializer: D,
    ) -> ::std::result::Result<::std::option::Option<::std::string::String>, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        <::std::option::Option<::std::string::String> as ::serde::Deserialize>::deserialize(deserializer)
    }
    fn deserialize_nonnegative_int32<'de, D>(deserializer: D) -> ::std::result::Result<i32, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        let value = <i32 as ::serde::Deserialize>::deserialize(deserializer)?;
        if value < 0 {
            return Err(<D::Error as ::serde::de::Error>::custom("integer must be nonnegative"));
        }
        Ok(value)
    }
    fn deserialize_utc_datetime<'de, D>(
        deserializer: D,
    ) -> ::std::result::Result<::chrono::DateTime<::chrono::offset::Utc>, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        let value = <::std::string::String as ::serde::Deserialize>::deserialize(deserializer)?;
        if !value.ends_with('Z') {
            return Err(<D::Error as ::serde::de::Error>::custom("date-time must use the UTC Z suffix"));
        }
        value.parse().map_err(<D::Error as ::serde::de::Error>::custom)
    }
"#;
    source
        .replacen("pub mod types {\n", &format!("pub mod types {{\n{helpers}"), 1)
        .replacen(
            nullable_field,
            "        #[serde(\n            rename = \"requiredNullable\",\n            deserialize_with = \"deserialize_required_nullable\"\n        )]\n        pub required_nullable: ::std::option::Option<::std::string::String>,",
            1,
        )
        .replacen(
            count_field,
            "        #[serde(deserialize_with = \"deserialize_nonnegative_int32\")]\n        pub count: i32,",
            1,
        )
        .replacen(
            attempt_field,
            "        Ready {\n            #[serde(deserialize_with = \"deserialize_nonnegative_int32\")]\n            attempt: i32,\n        },",
            1,
        )
        .replacen(
            date_time_field,
            "        #[serde(\n            rename = \"occurredAt\",\n            deserialize_with = \"deserialize_utc_datetime\"\n        )]\n        pub occurred_at: ::chrono::DateTime<::chrono::offset::Utc>,",
            1,
        )
}
