use std::{env, fs, path::PathBuf};

fn main() {
    let package_root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..");
    let spec_path = package_root.join("openapi/contract-proof.openapi.json");
    let output_path = package_root.join("rust/src/generated.rs");

    let spec =
        serde_json::from_slice(&fs::read(spec_path).expect("read committed OpenAPI document"))
            .expect("parse OpenAPI document");
    let tokens = progenitor::Generator::default()
        .generate_tokens(&spec)
        .expect("generate Progenitor client");
    let syntax = syn::parse2(tokens).expect("parse generated Rust");
    let source = enforce_ast_wire_semantics(enforce_wire_semantics(format!(
        "// Generated by Progenitor 0.14.0. Do not edit.\n{}",
        prettyplease::unparse(&syntax)
    )));

    fs::write(output_path, source).expect("write generated Rust client");
}

fn enforce_wire_semantics(source: String) -> String {
    let nullable_field = "        #[serde(rename = \"requiredNullable\")]\n        pub required_nullable: ::std::option::Option<::std::string::String>,";
    let count_field = "        pub count: i32,";
    let attempt_field = "        Ready { attempt: i32 },";
    let date_time_field = "        #[serde(rename = \"occurredAt\")]\n        pub occurred_at: ::chrono::DateTime<::chrono::offset::Utc>,";
    assert!(
        source.contains(nullable_field),
        "Progenitor required-nullable mapping changed"
    );
    assert!(
        source.contains(count_field),
        "Progenitor bounded count mapping changed"
    );
    assert!(
        source.contains(attempt_field),
        "Progenitor bounded attempt mapping changed"
    );
    assert!(
        source.contains(date_time_field),
        "Progenitor date-time mapping changed"
    );

    let helpers = r#"    fn deserialize_required_nullable<'de, D>(
        deserializer: D,
    ) -> ::std::result::Result<::std::option::Option<::std::string::String>, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        <::std::option::Option<::std::string::String> as ::serde::Deserialize>::deserialize(deserializer)
    }
    fn deserialize_nonnegative_int32<'de, D>(deserializer: D) -> ::std::result::Result<i32, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        let value = <i32 as ::serde::Deserialize>::deserialize(deserializer)?;
        if value < 0 {
            return Err(<D::Error as ::serde::de::Error>::custom("integer must be nonnegative"));
        }
        Ok(value)
    }
    fn deserialize_utc_datetime<'de, D>(
        deserializer: D,
    ) -> ::std::result::Result<::chrono::DateTime<::chrono::offset::Utc>, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        let value = <::std::string::String as ::serde::Deserialize>::deserialize(deserializer)?;
        if !value.ends_with('Z') {
            return Err(<D::Error as ::serde::de::Error>::custom("date-time must use the UTC Z suffix"));
        }
        value.parse().map_err(<D::Error as ::serde::de::Error>::custom)
    }
    fn deserialize_optional_utc_datetime<'de, D>(
        deserializer: D,
    ) -> ::std::result::Result<::std::option::Option<::chrono::DateTime<::chrono::offset::Utc>>, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        let value = <::std::option::Option<::std::string::String> as ::serde::Deserialize>::deserialize(deserializer)?;
        value
            .map(|value| {
                if !value.ends_with('Z') {
                    return Err(<D::Error as ::serde::de::Error>::custom("date-time must use the UTC Z suffix"));
                }
                value.parse().map_err(<D::Error as ::serde::de::Error>::custom)
            })
            .transpose()
    }
    fn deserialize_ranked_freshness_seconds<'de, D>(deserializer: D) -> ::std::result::Result<i32, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        let value = <i32 as ::serde::Deserialize>::deserialize(deserializer)?;
        if value != 3600 {
            return Err(<D::Error as ::serde::de::Error>::custom("ranked freshness must be 3600 seconds"));
        }
        Ok(value)
    }
    fn deserialize_career_freshness_seconds<'de, D>(deserializer: D) -> ::std::result::Result<i32, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        let value = <i32 as ::serde::Deserialize>::deserialize(deserializer)?;
        if value != 43200 {
            return Err(<D::Error as ::serde::de::Error>::custom("career freshness must be 43200 seconds"));
        }
        Ok(value)
    }
    fn deserialize_fraction<'de, D>(deserializer: D) -> ::std::result::Result<f64, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        let value = <f64 as ::serde::Deserialize>::deserialize(deserializer)?;
        if !value.is_finite() || !(0.0..=1.0).contains(&value) {
            return Err(<D::Error as ::serde::de::Error>::custom("number must be between 0 and 1"));
        }
        Ok(value)
    }
    fn deserialize_zero_int32<'de, D>(deserializer: D) -> ::std::result::Result<i32, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        let value = <i32 as ::serde::Deserialize>::deserialize(deserializer)?;
        if value != 0 {
            return Err(<D::Error as ::serde::de::Error>::custom("integer must be zero"));
        }
        Ok(value)
    }
    fn deserialize_bounded_nonzero_u64<'de, D>(
        deserializer: D,
    ) -> ::std::result::Result<::std::num::NonZeroU64, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        let value = <u64 as ::serde::Deserialize>::deserialize(deserializer)?;
        if value > i32::MAX as u64 {
            return Err(<D::Error as ::serde::de::Error>::custom("integer exceeds int32 maximum"));
        }
        ::std::num::NonZeroU64::new(value)
            .ok_or_else(|| <D::Error as ::serde::de::Error>::custom("integer must be positive"))
    }
    fn deserialize_bounded_nonzero_u32<'de, D>(
        deserializer: D,
    ) -> ::std::result::Result<::std::num::NonZeroU32, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        let value = <u32 as ::serde::Deserialize>::deserialize(deserializer)?;
        if value > i32::MAX as u32 {
            return Err(<D::Error as ::serde::de::Error>::custom("integer exceeds int32 maximum"));
        }
        ::std::num::NonZeroU32::new(value)
            .ok_or_else(|| <D::Error as ::serde::de::Error>::custom("integer must be positive"))
    }
    fn deserialize_optional_bounded_nonzero_u32<'de, D>(
        deserializer: D,
    ) -> ::std::result::Result<::std::option::Option<::std::num::NonZeroU32>, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        let value = <::std::option::Option<u32> as ::serde::Deserialize>::deserialize(deserializer)?;
        value.map(|value| {
            if value > i32::MAX as u32 {
                return Err(<D::Error as ::serde::de::Error>::custom("integer exceeds int32 maximum"));
            }
            ::std::num::NonZeroU32::new(value)
                .ok_or_else(|| <D::Error as ::serde::de::Error>::custom("integer must be positive"))
        }).transpose()
    }
    fn is_visible_character(value: char) -> bool {
        !matches!(
            ::unicode_general_category::get_general_category(value),
            ::unicode_general_category::GeneralCategory::SpaceSeparator
                | ::unicode_general_category::GeneralCategory::LineSeparator
                | ::unicode_general_category::GeneralCategory::ParagraphSeparator
                | ::unicode_general_category::GeneralCategory::Format
        )
    }
"#;
    let source = source
        .replacen("pub mod types {\n", &format!("pub mod types {{\n{helpers}"), 1)
        .replacen(
            nullable_field,
            "        #[serde(\n            rename = \"requiredNullable\",\n            deserialize_with = \"deserialize_required_nullable\"\n        )]\n        pub required_nullable: ::std::option::Option<::std::string::String>,",
            1,
        )
        .replacen(
            count_field,
            "        #[serde(deserialize_with = \"deserialize_nonnegative_int32\")]\n        pub count: i32,",
            1,
        )
        .replacen(
            attempt_field,
            "        Ready {\n            #[serde(deserialize_with = \"deserialize_nonnegative_int32\")]\n            attempt: i32,\n        },",
            1,
        )
        .replacen(
            date_time_field,
            "        #[serde(\n            rename = \"occurredAt\",\n            deserialize_with = \"deserialize_utc_datetime\"\n        )]\n        pub occurred_at: ::chrono::DateTime<::chrono::offset::Utc>,",
            1,
        );
    enforce_career_wire_semantics(enforce_ranked_wire_semantics(source))
}

fn enforce_ranked_wire_semantics(source: String) -> String {
    let start = source
        .find("    ///`PlayerRankedProfile`")
        .expect("generated ranked profile start changed");
    let relative_end = source[start..]
        .find("    ///`PlayerRefreshResponse`")
        .expect("generated ranked profile end changed");
    let end = start + relative_end;
    let mut ranked = source[start..end].to_owned();

    for field in ["games", "peak_rating", "rating", "wins"] {
        let original = format!("        pub {field}: i32,");
        assert!(
            ranked.contains(&original),
            "generated ranked {field} field changed"
        );
        ranked = ranked.replace(
            &original,
            &format!(
                "        #[serde(deserialize_with = \"deserialize_nonnegative_int32\")]\n        pub {field}: i32,"
            ),
        );
    }

    for field in ["brawlhalla_id", "brawlhalla_id_one", "brawlhalla_id_two"] {
        let original = format!("        pub {field}: ::std::num::NonZeroU64,");
        if ranked.contains(&original) {
            ranked = ranked.replace(
                &original,
                &format!(
                    "        #[serde(deserialize_with = \"deserialize_bounded_nonzero_u64\")]\n        pub {field}: ::std::num::NonZeroU64,"
                ),
            );
        }
    }
    let legend_id = "        pub legend_id: ::std::num::NonZeroU32,";
    assert!(
        ranked.contains(legend_id),
        "generated ranked legend ID changed"
    );
    ranked = ranked.replace(
        legend_id,
        "        #[serde(deserialize_with = \"deserialize_bounded_nonzero_u32\")]\n        pub legend_id: ::std::num::NonZeroU32,",
    );
    for field in ["global_rank", "region_rank"] {
        let original =
            format!("        pub {field}: ::std::option::Option<::std::num::NonZeroU32>,");
        if ranked.contains(&original) {
            ranked = ranked.replace(
                &original,
                &format!(
                    "        #[serde(deserialize_with = \"deserialize_optional_bounded_nonzero_u32\")]\n        pub {field}: ::std::option::Option<::std::num::NonZeroU32>,"
                ),
            );
        }
    }

    let checked_at = "        #[serde(rename = \"checkedAt\")]\n        pub checked_at: ::chrono::DateTime<::chrono::offset::Utc>,";
    let last_success_at = "        #[serde(rename = \"lastSuccessAt\")]\n        pub last_success_at: ::std::option::Option<\n            ::chrono::DateTime<::chrono::offset::Utc>,\n        >,";
    let recorded_at = "        #[serde(rename = \"recordedAt\")]\n        pub recorded_at: ::chrono::DateTime<::chrono::offset::Utc>,";
    let freshness =
        "        #[serde(rename = \"freshForSeconds\")]\n        pub fresh_for_seconds: i32,";
    let second_player =
        "        #[serde(rename = \"secondPlayerId\")]\n        pub second_player_id: i32,";
    for expected in [
        checked_at,
        last_success_at,
        recorded_at,
        freshness,
        second_player,
    ] {
        assert!(
            ranked.contains(expected),
            "generated ranked field mapping changed: {expected}"
        );
    }

    ranked = ranked
        .replacen(
            checked_at,
            "        #[serde(\n            rename = \"checkedAt\",\n            deserialize_with = \"deserialize_utc_datetime\"\n        )]\n        pub checked_at: ::chrono::DateTime<::chrono::offset::Utc>,",
            1,
        )
        .replacen(
            last_success_at,
            "        #[serde(\n            rename = \"lastSuccessAt\",\n            deserialize_with = \"deserialize_optional_utc_datetime\"\n        )]\n        pub last_success_at: ::std::option::Option<\n            ::chrono::DateTime<::chrono::offset::Utc>,\n        >,",
            1,
        )
        .replace(
            recorded_at,
            "        #[serde(\n            rename = \"recordedAt\",\n            deserialize_with = \"deserialize_utc_datetime\"\n        )]\n        pub recorded_at: ::chrono::DateTime<::chrono::offset::Utc>,",
        )
        .replacen(
            freshness,
            "        #[serde(\n            rename = \"freshForSeconds\",\n            deserialize_with = \"deserialize_ranked_freshness_seconds\"\n        )]\n        pub fresh_for_seconds: i32,",
            1,
        )
        .replace(
            second_player,
            "        #[serde(\n            rename = \"secondPlayerId\",\n            deserialize_with = \"deserialize_zero_int32\"\n        )]\n        pub second_player_id: i32,",
        );

    let non_visible_check = "if value.chars().count() < 1usize {";
    assert!(
        ranked.matches(non_visible_check).count() >= 3,
        "generated ranked visible-string checks changed"
    );
    ranked = ranked.replace(
        non_visible_check,
        "if value.chars().count() < 1usize || !value.chars().any(is_visible_character) {",
    );

    format!("{}{}{}", &source[..start], ranked, &source[end..])
}

fn enforce_career_wire_semantics(source: String) -> String {
    let start = source
        .find("    ///`PlayerCareerProfile`")
        .expect("generated career profile start changed");
    let relative_end = source[start..]
        .find("    ///`PlayerRankedProfile`")
        .expect("generated career profile end changed");
    let end = start + relative_end;
    let mut career = source[start..end].to_owned();

    let profile = r#"    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    #[serde(deny_unknown_fields)]
    pub struct PlayerCareerProfile {
        #[serde(rename = "brawlhallaId")]
        pub brawlhalla_id: ::std::num::NonZeroU64,
        #[serde(rename = "checkedAt")]
        pub checked_at: ::chrono::DateTime<::chrono::offset::Utc>,
        #[serde(rename = "freshForSeconds")]
        pub fresh_for_seconds: i32,
        pub freshness: PlayerCareerProfileFreshness,
        #[serde(rename = "lastSuccessAt")]
        pub last_success_at: ::std::option::Option<
            ::chrono::DateTime<::chrono::offset::Utc>,
        >,
        pub snapshot: PlayerCareerSnapshot,
    }"#;
    assert!(
        career.contains(profile),
        "generated career profile mapping changed"
    );
    let validated_profile = r#"    #[derive(::serde::Serialize, Clone, Debug)]
    #[serde(deny_unknown_fields)]
    pub struct PlayerCareerProfile {
        #[serde(rename = "brawlhallaId")]
        pub brawlhalla_id: ::std::num::NonZeroU64,
        #[serde(rename = "checkedAt")]
        pub checked_at: ::chrono::DateTime<::chrono::offset::Utc>,
        #[serde(rename = "freshForSeconds")]
        pub fresh_for_seconds: i32,
        pub freshness: PlayerCareerProfileFreshness,
        #[serde(rename = "lastSuccessAt")]
        pub last_success_at: ::std::option::Option<
            ::chrono::DateTime<::chrono::offset::Utc>,
        >,
        pub snapshot: PlayerCareerSnapshot,
    }
    impl<'de> ::serde::Deserialize<'de> for PlayerCareerProfile {
        fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
        where
            D: ::serde::Deserializer<'de>,
        {
            #[derive(::serde::Deserialize)]
            #[serde(deny_unknown_fields)]
            struct Wire {
                #[serde(rename = "brawlhallaId", deserialize_with = "deserialize_bounded_nonzero_u64")]
                brawlhalla_id: ::std::num::NonZeroU64,
                #[serde(rename = "checkedAt", deserialize_with = "deserialize_utc_datetime")]
                checked_at: ::chrono::DateTime<::chrono::offset::Utc>,
                #[serde(rename = "freshForSeconds", deserialize_with = "deserialize_career_freshness_seconds")]
                fresh_for_seconds: i32,
                freshness: PlayerCareerProfileFreshness,
                #[serde(rename = "lastSuccessAt", deserialize_with = "deserialize_optional_utc_datetime")]
                last_success_at: ::std::option::Option<::chrono::DateTime<::chrono::offset::Utc>>,
                snapshot: PlayerCareerSnapshot,
            }
            let wire = <Wire as ::serde::Deserialize>::deserialize(deserializer)?;
            let unavailable = wire.last_success_at.is_none()
                && matches!(wire.freshness, PlayerCareerProfileFreshness::Unavailable)
                && wire.snapshot.0.is_none();
            let available = wire.last_success_at.is_some()
                && !matches!(wire.freshness, PlayerCareerProfileFreshness::Unavailable)
                && wire.snapshot.0.is_some();
            if !unavailable && !available {
                return Err(<D::Error as ::serde::de::Error>::custom("career availability fields are inconsistent"));
            }
            if let Some(snapshot) = &wire.snapshot.0 {
                if snapshot.combat.wins > snapshot.combat.games
                    || snapshot.legends.iter().any(|legend| legend.wins > legend.games)
                {
                    return Err(<D::Error as ::serde::de::Error>::custom("career wins cannot exceed games"));
                }
            }
            Ok(Self {
                brawlhalla_id: wire.brawlhalla_id,
                checked_at: wire.checked_at,
                fresh_for_seconds: wire.fresh_for_seconds,
                freshness: wire.freshness,
                last_success_at: wire.last_success_at,
                snapshot: wire.snapshot,
            })
        }
    }"#;
    career = career.replacen(profile, validated_profile, 1);

    {
        let field = "brawlhalla_id";
        let original = format!("        pub {field}: ::std::num::NonZeroU64,");
        if career.contains(&original) {
            career = career.replace(
                &original,
                &format!("        #[serde(deserialize_with = \"deserialize_bounded_nonzero_u64\")]\n        pub {field}: ::std::num::NonZeroU64,"),
            );
        }
    }
    let legend_id = "        pub legend_id: ::std::num::NonZeroU32,";
    assert!(
        career.contains(legend_id),
        "generated career legend ID changed"
    );
    career = career.replace(
        legend_id,
        "        #[serde(deserialize_with = \"deserialize_bounded_nonzero_u32\")]\n        pub legend_id: ::std::num::NonZeroU32,",
    );
    let xp_percentage = "        pub xp_percentage: f64,";
    assert!(
        career.matches(xp_percentage).count() >= 2,
        "generated career fractions changed"
    );
    career = career.replace(
        xp_percentage,
        "        #[serde(deserialize_with = \"deserialize_fraction\")]\n        pub xp_percentage: f64,",
    );

    let mut bounded = String::with_capacity(career.len());
    for line in career.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("pub ")
            && trimmed.ends_with(": i32,")
            && !trimmed.contains("fresh_for_seconds")
        {
            let indent = &line[..line.len() - line.trim_start().len()];
            bounded.push_str(indent);
            bounded.push_str("#[serde(deserialize_with = \"deserialize_nonnegative_int32\")]\n");
        }
        bounded.push_str(line);
        bounded.push('\n');
    }
    career = bounded;

    let non_visible_check = "if value.chars().count() < 1usize {";
    assert!(
        career.matches(non_visible_check).count() >= 2,
        "generated career visible-string checks changed"
    );
    career = career.replace(
        non_visible_check,
        "if value.chars().count() < 1usize || !value.chars().any(is_visible_character) {",
    );

    format!(
        "{}{}\n{}",
        &source[..start],
        career.trim_end(),
        &source[end..]
    )
}

fn enforce_ast_wire_semantics(source: String) -> String {
    let mut syntax = syn::parse_file(&source).expect("parse postprocessed generated Rust");

    {
        let types = syntax
            .items
            .iter_mut()
            .find_map(|item| match item {
                syn::Item::Mod(module) if module.ident == "types" => {
                    module.content.as_mut().map(|(_, items)| items)
                }
                _ => None,
            })
            .expect("generated types module changed");

        let mut desktop_count = 0;
        let mut ranked_profile_count = 0;
        for item in types.iter_mut() {
            let syn::Item::Struct(item_struct) = item else {
                continue;
            };
            if item_struct.ident == "DesktopRankedLookupPlayer" {
                desktop_count += 1;
                let field = item_struct
                    .fields
                    .iter_mut()
                    .find(|field| {
                        field
                            .ident
                            .as_ref()
                            .is_some_and(|ident| ident == "brawlhalla_id")
                    })
                    .expect("generated desktop player ID field changed");
                field
                    .attrs
                    .retain(|attribute| !attribute.path().is_ident("serde"));
                field.attrs.push(syn::parse_quote!(
                    #[serde(
                        rename = "brawlhallaId",
                        deserialize_with = "deserialize_bounded_nonzero_u64"
                    )]
                ));
            } else if item_struct.ident == "PlayerRankedProfileInner" {
                ranked_profile_count += 1;
                remove_deserialize_derive(&mut item_struct.attrs);
                for field in item_struct.fields.iter_mut() {
                    let name = field
                        .ident
                        .as_ref()
                        .expect("generated ranked profile field became unnamed")
                        .to_string();
                    field
                        .attrs
                        .retain(|attribute| !attribute.path().is_ident("serde"));
                    let rename = match name.as_str() {
                        "brawlhalla_id" => Some("brawlhallaId"),
                        "checked_at" => Some("checkedAt"),
                        "fresh_for_seconds" => Some("freshForSeconds"),
                        "last_success_at" => Some("lastSuccessAt"),
                        "sparse_pulse" => Some("sparsePulse"),
                        "freshness" | "snapshot" => None,
                        _ => panic!("generated ranked profile field changed: {name}"),
                    };
                    if let Some(rename) = rename {
                        field
                            .attrs
                            .push(syn::parse_quote!(#[serde(rename = #rename)]));
                    }
                }
            }
        }
        assert_eq!(desktop_count, 1, "generated desktop lookup type changed");
        assert_eq!(
            ranked_profile_count, 1,
            "generated ranked profile type changed"
        );
        types.push(ranked_profile_deserialize_impl());
    }

    let mut desktop_method_count = 0;
    for item in syntax.items.iter_mut() {
        let syn::Item::Impl(item_impl) = item else {
            continue;
        };
        for impl_item in &mut item_impl.items {
            let syn::ImplItem::Fn(method) = impl_item else {
                continue;
            };
            if method.sig.ident != "get_desktop_ranked_lookup" {
                continue;
            }
            desktop_method_count += 1;
            let guard: syn::Stmt = syn::parse_quote! {
                if response.status().as_u16() == 200u16 {
                    const MAX_DESKTOP_RESPONSE_BYTES: u64 = 256 * 1024;
                    let content_length = response.content_length().ok_or_else(|| {
                        Error::Custom("desktop ranked response omitted Content-Length".to_string())
                    })?;
                    if content_length > MAX_DESKTOP_RESPONSE_BYTES {
                        return Err(Error::Custom(
                            "desktop ranked response exceeded the size limit".to_string(),
                        ));
                    }
                }
            };
            let final_expression = method
                .block
                .stmts
                .len()
                .checked_sub(1)
                .expect("generated desktop operation body changed");
            method.block.stmts.insert(final_expression, guard);
        }
    }
    assert_eq!(
        desktop_method_count, 1,
        "generated desktop lookup operation changed"
    );

    format!(
        "// Generated by Progenitor 0.14.0. Do not edit.\n{}",
        prettyplease::unparse(&syntax)
    )
}

fn remove_deserialize_derive(attributes: &mut [syn::Attribute]) {
    let mut removed = false;
    for attribute in attributes {
        if !attribute.path().is_ident("derive") {
            continue;
        }
        let derives = attribute
            .parse_args_with(
                syn::punctuated::Punctuated::<syn::Path, syn::Token![,]>::parse_terminated,
            )
            .expect("parse generated ranked profile derives");
        let retained: syn::punctuated::Punctuated<syn::Path, syn::Token![,]> = derives
            .into_iter()
            .filter(|path| {
                let is_deserialize = path
                    .segments
                    .last()
                    .is_some_and(|segment| segment.ident == "Deserialize");
                removed |= is_deserialize;
                !is_deserialize
            })
            .collect();
        *attribute = syn::parse_quote!(#[derive(#retained)]);
    }
    assert!(
        removed,
        "generated ranked profile Deserialize derive changed"
    );
}

fn ranked_profile_deserialize_impl() -> syn::Item {
    syn::parse_quote! {
        impl<'de> ::serde::Deserialize<'de> for PlayerRankedProfileInner {
            fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
            where
                D: ::serde::Deserializer<'de>,
            {
                #[derive(::serde::Deserialize)]
                #[serde(deny_unknown_fields)]
                struct Wire {
                    #[serde(
                        rename = "brawlhallaId",
                        deserialize_with = "deserialize_bounded_nonzero_u64"
                    )]
                    brawlhalla_id: ::std::num::NonZeroU64,
                    #[serde(
                        rename = "checkedAt",
                        deserialize_with = "deserialize_utc_datetime"
                    )]
                    checked_at: ::chrono::DateTime<::chrono::offset::Utc>,
                    #[serde(
                        rename = "freshForSeconds",
                        deserialize_with = "deserialize_ranked_freshness_seconds"
                    )]
                    fresh_for_seconds: i32,
                    freshness: PlayerRankedProfileInnerFreshness,
                    #[serde(
                        rename = "lastSuccessAt",
                        deserialize_with = "deserialize_optional_utc_datetime"
                    )]
                    last_success_at: ::std::option::Option<
                        ::chrono::DateTime<::chrono::offset::Utc>,
                    >,
                    snapshot: PlayerRankedSnapshot,
                    #[serde(rename = "sparsePulse")]
                    sparse_pulse: ::std::option::Option<PlayerRankedProfileInnerSparsePulse>,
                }
                let wire = <Wire as ::serde::Deserialize>::deserialize(deserializer)?;
                let unavailable = wire.last_success_at.is_none()
                    && matches!(
                        wire.freshness,
                        PlayerRankedProfileInnerFreshness::Unavailable
                    )
                    && wire.snapshot.0.is_none();
                let available = wire.last_success_at.is_some()
                    && !matches!(
                        wire.freshness,
                        PlayerRankedProfileInnerFreshness::Unavailable
                    )
                    && wire.snapshot.0.is_some();
                if !unavailable && !available {
                    return Err(<D::Error as ::serde::de::Error>::custom(
                        "ranked availability fields are inconsistent",
                    ));
                }
                if wire.sparse_pulse.is_some() && !available {
                    return Err(<D::Error as ::serde::de::Error>::custom(
                        "sparse pulse evidence requires canonical ranked state",
                    ));
                }
                if wire.sparse_pulse.as_ref().is_some_and(|pulse| {
                    pulse
                        .last_success_at
                        .is_some_and(|last_success_at| last_success_at > pulse.checked_at)
                }) {
                    return Err(<D::Error as ::serde::de::Error>::custom(
                        "pulse success cannot be later than its latest check",
                    ));
                }
                Ok(Self {
                    brawlhalla_id: wire.brawlhalla_id,
                    checked_at: wire.checked_at,
                    fresh_for_seconds: wire.fresh_for_seconds,
                    freshness: wire.freshness,
                    last_success_at: wire.last_success_at,
                    snapshot: wire.snapshot,
                    sparse_pulse: wire.sparse_pulse,
                })
            }
        }
    }
}
