[package]
name = "brawltome-detection"
version.workspace = true
edition.workspace = true

[dependencies]
brawltome-events.workspace = true
serde.workspace = true
log.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "sync", "macros", "time"] }
memchr = "2"

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
