import type { ArchitecturePolicy } from './types'

export const currentArchitecturePolicy: ArchitecturePolicy = {
  roles: {
    '@brawltome/api': 'application',
    '@brawltome/desktop': 'application',
    '@brawltome/discord-bot': 'application',
    '@brawltome/web': 'application',
    '@brawltome/bhapi': 'adapter',
    '@brawltome/database': 'adapter',
    '@brawltome/database-migrations': 'tooling',
    '@brawltome/launch-parity': 'tooling',
    '@brawltome/game-data': 'foundation',
    '@brawltome/replay-format': 'legacy',
    '@brawltome/shared': 'legacy',
    '@brawltome/ui': 'foundation',
    '@brawltome/architecture': 'tooling',
    '@brawltome/accounts': 'capability',
    '@brawltome/clan': 'capability',
    '@brawltome/contracts': 'contracts',
    '@brawltome/identity': 'capability',
    '@brawltome/matchmaking': 'legacy',
    '@brawltome/player': 'capability',
    '@brawltome/ranking': 'capability',
    '@brawltome/request-admission': 'capability',
    '@brawltome/refresh-operations': 'capability',
  },
  allowedExports: {
    '@brawltome/api': ['.'],
    '@brawltome/desktop': [],
    '@brawltome/discord-bot': [],
    '@brawltome/web': [],
    '@brawltome/bhapi': ['.'],
    '@brawltome/database': ['.'],
    '@brawltome/database-migrations': [],
    '@brawltome/launch-parity': [],
    '@brawltome/game-data': ['.', './reference-data'],
    '@brawltome/replay-format': ['.'],
    '@brawltome/shared': ['.', './constants', './weapons'],
    '@brawltome/ui': ['.'],
    '@brawltome/architecture': ['.'],
    '@brawltome/accounts': ['.', './composition'],
    '@brawltome/clan': ['.'],
    '@brawltome/contracts': ['.'],
    '@brawltome/identity': ['.', './composition'],
    '@brawltome/matchmaking': ['.'],
    '@brawltome/player': ['.', './composition'],
    '@brawltome/ranking': ['.', './composition'],
    '@brawltome/request-admission': ['.', './composition'],
    '@brawltome/refresh-operations': ['.', './composition'],
  },
  capabilityDependencies: {
    '@brawltome/accounts': [],
    '@brawltome/clan': [],
    '@brawltome/identity': [],
    '@brawltome/player': [],
    '@brawltome/ranking': [],
    '@brawltome/request-admission': [],
    '@brawltome/refresh-operations': [],
  },
  compositionImporters: ['@brawltome/api', '@brawltome/database-migrations'],
  contractsDependencies: ['@brawltome/game-data'],
  localImportAliases: {
    '@brawltome/desktop': ['@/'],
    '@brawltome/web': ['@/'],
  },
  workspaceRoleDependencies: {
    '@brawltome/database-migrations': ['capability'],
  },
  exceptions: [
    {
      id: 'v2-player-compatibility-export',
      rule: 'package-export',
      importer: '@brawltome/player',
      files: ['packages/contexts/player/package.json'],
      importPath: './v2-compatibility',
      reason: 'Existing API and Rankings callers still require the frozen V2 profile graph and repository port.',
      issue: '#227',
      expiresWhen: 'All V2 player profile and repository callers migrate to narrow capability interfaces.',
    },
    {
      id: 'v2-api-router-export',
      rule: 'package-export',
      importer: '@brawltome/api',
      files: ['apps/api/package.json'],
      importPath: './router',
      reason: 'V2 clients consume the API router type through an application export.',
      issue: '#186',
      expiresWhen: 'Canonical tRPC contracts no longer originate from API application source.',
    },
    {
      id: 'v2-matchmaking-database-adapter',
      rule: 'role-dependency',
      importer: '@brawltome/matchmaking',
      dependency: '@brawltome/database',
      files: ['packages/contexts/matchmaking/package.json', 'packages/contexts/matchmaking/match.repo.ts'],
      importPath: '@brawltome/database',
      reason: 'Frozen V2 Matchmaking consumes the broad shared database package.',
      issue: '#227',
      expiresWhen: 'Out-of-scope V2 package paths are removed from the final topology.',
    },
    {
      id: 'v2-matchmaking-replay-package',
      rule: 'role-dependency',
      importer: '@brawltome/matchmaking',
      dependency: '@brawltome/replay-format',
      files: [
        'packages/contexts/matchmaking/package.json',
        'packages/contexts/matchmaking/commands/ingestReplay.ts',
        'packages/contexts/matchmaking/commands/backfillPending.ts',
        'packages/contexts/matchmaking/tests/ingestReplay.test.ts',
        'packages/contexts/matchmaking/tests/backfillPending.test.ts',
      ],
      importPath: '@brawltome/replay-format',
      reason: 'Frozen V2 Matchmaking consumes the out-of-scope Replay Format package.',
      issue: '#227',
      expiresWhen: 'Out-of-scope V2 package paths are removed from the final topology.',
    },
    {
      id: 'v2-matchmaking-shared-package',
      rule: 'role-dependency',
      importer: '@brawltome/matchmaking',
      dependency: '@brawltome/shared',
      files: ['packages/contexts/matchmaking/package.json'],
      importPath: '@brawltome/shared',
      reason: 'Frozen V2 Matchmaking declares the mixed Shared package.',
      issue: '#227',
      expiresWhen: 'Out-of-scope V2 package paths are removed from the final topology.',
    },
    {
      id: 'v2-shared-bhapi-adapter',
      rule: 'role-dependency',
      importer: '@brawltome/shared',
      dependency: '@brawltome/bhapi',
      files: ['packages/shared/package.json', 'packages/shared/src/game-data.ts', 'packages/shared/src/queue.ts'],
      importPath: '@brawltome/bhapi',
      reason: 'The mixed V2 Shared package directly consumes the broad source adapter.',
      issue: '#227',
      expiresWhen: 'Shared responsibilities move behind owned capabilities and earned adapters.',
    },
    {
      id: 'v2-shared-database-adapter',
      rule: 'role-dependency',
      importer: '@brawltome/shared',
      dependency: '@brawltome/database',
      files: ['packages/shared/package.json', 'packages/shared/src/game-data.ts'],
      importPath: '@brawltome/database',
      reason: 'The mixed V2 Shared package directly consumes the broad database package.',
      issue: '#227',
      expiresWhen: 'Shared responsibilities move behind owned capabilities and earned adapters.',
    },
    {
      id: 'v2-shared-game-data-foundation',
      rule: 'role-dependency',
      importer: '@brawltome/shared',
      dependency: '@brawltome/game-data',
      files: ['packages/shared/package.json', 'packages/shared/src/game-data.ts', 'packages/shared/src/weapons.ts'],
      reason: 'The mixed V2 Shared package preserves compatibility wrappers over Game Reference Data.',
      issue: '#185',
      expiresWhen: 'Capability callers consume injected game references instead of the mixed Shared package.',
    },
    {
      id: 'v2-web-api-router-client-undeclared',
      rule: 'undeclared-dependency',
      importer: '@brawltome/web',
      dependency: '@brawltome/api',
      files: ['apps/web/src/lib/trpc.ts'],
      importPath: '@brawltome/api/router',
      reason: 'The V2 web client imports its router type from the API application.',
      issue: '#186',
      expiresWhen: 'Canonical tRPC contracts no longer originate from API application source.',
    },
    {
      id: 'v2-web-api-router-client-app-import',
      rule: 'app-to-app',
      importer: '@brawltome/web',
      dependency: '@brawltome/api',
      files: ['apps/web/src/lib/trpc.ts'],
      importPath: '@brawltome/api/router',
      reason: 'The V2 web client imports its router type from the API application.',
      issue: '#186',
      expiresWhen: 'Canonical tRPC contracts no longer originate from API application source.',
    },
    {
      id: 'v2-web-api-router-server-undeclared',
      rule: 'undeclared-dependency',
      importer: '@brawltome/web',
      dependency: '@brawltome/api',
      files: ['apps/web/src/lib/trpc-server.ts'],
      importPath: '@brawltome/api/router',
      reason: 'The V2 server-side web client imports its router type from the API application.',
      issue: '#186',
      expiresWhen: 'Canonical tRPC contracts no longer originate from API application source.',
    },
    {
      id: 'v2-web-api-router-server-app-import',
      rule: 'app-to-app',
      importer: '@brawltome/web',
      dependency: '@brawltome/api',
      files: ['apps/web/src/lib/trpc-server.ts'],
      importPath: '@brawltome/api/router',
      reason: 'The V2 server-side web client imports its router type from the API application.',
      issue: '#186',
      expiresWhen: 'Canonical tRPC contracts no longer originate from API application source.',
    },
    {
      id: 'v2-discord-api-router-undeclared',
      rule: 'undeclared-dependency',
      importer: '@brawltome/discord-bot',
      dependency: '@brawltome/api',
      files: ['apps/discord-bot/src/lib/trpc.ts'],
      importPath: '@brawltome/api/router',
      reason: 'The V2 Discord client imports its router type from the API application.',
      issue: '#186',
      expiresWhen: 'Canonical tRPC contracts no longer originate from API application source.',
    },
    {
      id: 'v2-discord-api-router-app-import',
      rule: 'app-to-app',
      importer: '@brawltome/discord-bot',
      dependency: '@brawltome/api',
      files: ['apps/discord-bot/src/lib/trpc.ts'],
      importPath: '@brawltome/api/router',
      reason: 'The V2 Discord client imports its router type from the API application.',
      issue: '#186',
      expiresWhen: 'Canonical tRPC contracts no longer originate from API application source.',
    },
    {
      id: 'v2-api-shared-package',
      rule: 'role-dependency',
      importer: '@brawltome/api',
      dependency: '@brawltome/shared',
      files: [
        'apps/api/package.json',
        'apps/api/src/serve.ts',
        'apps/api/src/worker.ts',
        'apps/api/src/router/clan.router.ts',
        'apps/api/src/router/player.router.ts',
        'apps/api/src/routes/matchmaking.routes.ts',
        'apps/api/src/trpc/context.ts',
        'apps/api/src/auth/routes.ts',
        'apps/api/tests/game-data.test.ts',
        'apps/api/tests/metrics.test.ts',
        'apps/api/tests/turnstile.test.ts',
        'apps/api/tests/queue.test.ts',
        'apps/api/tests/rate-limit.test.ts',
      ],
      reason: 'The V2 shared package mixes runtime infrastructure and product helpers.',
      issue: '#227',
      expiresWhen: 'API callers use owned capabilities, foundations, contracts, and earned adapters.',
    },
    {
      id: 'v2-api-matchmaking-package',
      rule: 'role-dependency',
      importer: '@brawltome/api',
      dependency: '@brawltome/matchmaking',
      files: [
        'apps/api/package.json',
        'apps/api/src/serve.ts',
        'apps/api/src/worker.ts',
        'apps/api/src/router/matchmaking.router.ts',
        'apps/api/src/routes/matchmaking.routes.ts',
        'apps/api/src/trpc/context.ts',
      ],
      reason: 'V2 Matchmaking remains frozen and is explicitly outside the V3 rewrite.',
      issue: '#227',
      expiresWhen: 'Out-of-scope V2 package paths are removed from the final topology.',
    },
    {
      id: 'v2-api-replay-package',
      rule: 'role-dependency',
      importer: '@brawltome/api',
      dependency: '@brawltome/replay-format',
      files: [
        'apps/api/package.json',
        'apps/api/src/worker.ts',
        'apps/api/src/routes/matchmaking.routes.ts',
        'apps/api/scripts/ingest-replay.ts',
      ],
      reason: 'V2 replay behavior remains frozen and is explicitly outside the V3 rewrite.',
      issue: '#227',
      expiresWhen: 'Out-of-scope V2 package paths are removed from the final topology.',
    },
    {
      id: 'v2-clan-database-adapter',
      rule: 'role-dependency',
      importer: '@brawltome/clan',
      dependency: '@brawltome/database',
      files: [
        'packages/contexts/clan/package.json',
        'packages/contexts/clan/clan.repo.ts',
        'packages/contexts/clan/commands/refresh-clan.ts',
        'packages/contexts/clan/tests/refresh-clan.test.ts',
      ],
      reason: 'The V2 Clan package consumes the broad shared database package.',
      issue: '#198',
      expiresWhen: 'Clans owns its persistence behind its narrow public interface.',
    },
    {
      id: 'v2-clan-bhapi-adapter',
      rule: 'role-dependency',
      importer: '@brawltome/clan',
      dependency: '@brawltome/bhapi',
      files: [
        'packages/contexts/clan/package.json',
        'packages/contexts/clan/commands/refresh-clan.ts',
        'packages/contexts/clan/tests/refresh-clan.test.ts',
      ],
      reason: 'The V2 Clan package directly consumes the broad source adapter.',
      issue: '#198',
      expiresWhen: 'Clans receives narrow source behavior through an internal seam.',
    },
    {
      id: 'v2-clan-shared-package',
      rule: 'role-dependency',
      importer: '@brawltome/clan',
      dependency: '@brawltome/shared',
      files: ['packages/contexts/clan/package.json', 'packages/contexts/clan/commands/discover-clan.ts'],
      reason: 'The V2 Clan package consumes mixed shared infrastructure.',
      issue: '#198',
      expiresWhen: 'Clans owns refresh behavior and uses narrow infrastructure interfaces.',
    },
    {
      id: 'v2-identity-player-link-database-adapter',
      rule: 'role-dependency',
      importer: '@brawltome/identity',
      dependency: '@brawltome/database',
      files: ['packages/contexts/identity/package.json', 'packages/contexts/identity/playerLink.repo.ts'],
      reason: 'The V2 player-link compatibility adapter remains on the shared database until Primary Player migration.',
      issue: '#204',
      expiresWhen: 'Primary Player verification replaces the V2 player-link adapter.',
    },
    {
      id: 'v2-player-database-adapter',
      rule: 'role-dependency',
      importer: '@brawltome/player',
      dependency: '@brawltome/database',
      files: [
        'packages/contexts/player/package.json',
        'packages/contexts/player/player.repo.ts',
        'packages/contexts/player/player.ts',
        'packages/contexts/player/commands/refresh-player.ts',
        'packages/contexts/player/commands/discover-player.ts',
        'packages/contexts/player/queries/get-effective-best-legend.ts',
        'packages/contexts/player/tests/get-effective-best-legend.test.ts',
        'packages/contexts/player/tests/refresh-ranked.test.ts',
        'packages/contexts/player/tests/refresh-stats.test.ts',
        'packages/contexts/player/tests/game-data-normalize.test.ts',
      ],
      reason: 'The V2 Player package consumes the broad shared database package.',
      issue: '#197',
      expiresWhen: 'Players owns its persistence behind its narrow public interface.',
    },
    {
      id: 'v2-player-bhapi-adapter',
      rule: 'role-dependency',
      importer: '@brawltome/player',
      dependency: '@brawltome/bhapi',
      files: [
        'packages/contexts/player/package.json',
        'packages/contexts/player/commands/refresh-player.ts',
        'packages/contexts/player/tests/refresh-ranked.test.ts',
        'packages/contexts/player/tests/refresh-stats.test.ts',
      ],
      reason: 'The V2 Player package directly consumes the broad source adapter.',
      issue: '#194',
      expiresWhen: 'Players receives canonical source behavior through private source seams.',
    },
    {
      id: 'v2-player-shared-package',
      rule: 'role-dependency',
      importer: '@brawltome/player',
      dependency: '@brawltome/shared',
      files: [
        'packages/contexts/player/package.json',
        'packages/contexts/player/player.repo.ts',
        'packages/contexts/player/player.ts',
        'packages/contexts/player/commands/refresh-player.ts',
        'packages/contexts/player/commands/discover-player.ts',
        'packages/contexts/player/queries/get-effective-best-legend.ts',
        'packages/contexts/player/queries/get-player.ts',
        'packages/contexts/player/tests/get-effective-best-legend.test.ts',
        'packages/contexts/player/tests/refresh-ranked.test.ts',
        'packages/contexts/player/tests/refresh-stats.test.ts',
        'packages/contexts/player/tests/game-data-normalize.test.ts',
      ],
      reason: 'The V2 Player package consumes mixed shared infrastructure and game data.',
      issue: '#197',
      expiresWhen: 'Players uses foundations and narrow infrastructure interfaces.',
    },
    {
      id: 'v2-ranking-bhapi-adapter',
      rule: 'role-dependency',
      importer: '@brawltome/ranking',
      dependency: '@brawltome/bhapi',
      files: ['packages/contexts/ranking/package.json'],
      reason: 'The V2 Ranking package declares the broad shared source adapter.',
      issue: '#202',
      expiresWhen: 'Rankings receives source behavior through a private narrow seam.',
    },
    {
      id: 'v2-ranking-database-adapter',
      rule: 'role-dependency',
      importer: '@brawltome/ranking',
      dependency: '@brawltome/database',
      files: [
        'packages/contexts/ranking/package.json',
        'packages/contexts/ranking/tests/sweep-upserts.test.ts',
        'packages/contexts/ranking/tests/get-leaderboard.test.ts',
      ],
      reason: 'The V2 Ranking package consumes the broad shared database package.',
      issue: '#202',
      expiresWhen: 'Rankings owns immutable snapshot persistence behind its public interface.',
    },
    {
      id: 'v2-ranking-shared-package',
      rule: 'role-dependency',
      importer: '@brawltome/ranking',
      dependency: '@brawltome/shared',
      files: [
        'packages/contexts/ranking/package.json',
        'packages/contexts/ranking/commands/sweep-leaderboards.ts',
        'packages/contexts/ranking/tests/sweep-leaderboards.test.ts',
      ],
      reason: 'The V2 Ranking package consumes mixed shared infrastructure.',
      issue: '#202',
      expiresWhen: 'Rankings uses narrow operations and observability interfaces.',
    },
    {
      id: 'v2-ranking-player-undeclared',
      rule: 'undeclared-dependency',
      importer: '@brawltome/ranking',
      dependency: '@brawltome/player',
      files: [
        'packages/contexts/ranking/commands/sweep-leaderboards.ts',
        'packages/contexts/ranking/queries/search-local.ts',
        'packages/contexts/ranking/queries/get-leaderboard.ts',
        'packages/contexts/ranking/tests/sweep-leaderboards.test.ts',
        'packages/contexts/ranking/tests/sweep-upserts.test.ts',
        'packages/contexts/ranking/tests/get-leaderboard.test.ts',
      ],
      reason: 'V2 Rankings reads Player repositories without declaring the package edge.',
      issue: '#200',
      expiresWhen: 'Discovery owns search and Rankings no longer reads Player repositories.',
    },
    {
      id: 'v2-ranking-player-capability-edge',
      rule: 'capability-allow-list',
      importer: '@brawltome/ranking',
      dependency: '@brawltome/player',
      files: [
        'packages/contexts/ranking/commands/sweep-leaderboards.ts',
        'packages/contexts/ranking/queries/search-local.ts',
        'packages/contexts/ranking/queries/get-leaderboard.ts',
        'packages/contexts/ranking/tests/sweep-leaderboards.test.ts',
        'packages/contexts/ranking/tests/sweep-upserts.test.ts',
        'packages/contexts/ranking/tests/get-leaderboard.test.ts',
      ],
      reason: 'V2 Rankings reads Player repositories across capability ownership.',
      issue: '#200',
      expiresWhen: 'Discovery owns search and Rankings no longer reads Player repositories.',
    },
    {
      id: 'v2-ranking-clan-undeclared',
      rule: 'undeclared-dependency',
      importer: '@brawltome/ranking',
      dependency: '@brawltome/clan',
      files: ['packages/contexts/ranking/queries/search-local.ts'],
      reason: 'V2 Rankings reads Clan repositories without declaring the package edge.',
      issue: '#200',
      expiresWhen: 'Discovery owns cross-kind search and Rankings no longer reads Clan repositories.',
    },
    {
      id: 'v2-ranking-clan-capability-edge',
      rule: 'capability-allow-list',
      importer: '@brawltome/ranking',
      dependency: '@brawltome/clan',
      files: ['packages/contexts/ranking/queries/search-local.ts'],
      reason: 'V2 Rankings reads Clan repositories across capability ownership.',
      issue: '#200',
      expiresWhen: 'Discovery owns cross-kind search and Rankings no longer reads Clan repositories.',
    },
    {
      id: 'v2-web-shared-package',
      rule: 'role-dependency',
      importer: '@brawltome/web',
      dependency: '@brawltome/shared',
      files: [
        'apps/web/package.json',
        'apps/web/src/lib/player-refresh.ts',
        'apps/web/src/components/player/LegendSection/LegendCard.tsx',
        'apps/web/src/components/clan/ClanProfile/index.tsx',
      ],
      reason: 'The V2 web application consumes constants and formatting from the mixed shared package.',
      issue: '#188',
      expiresWhen: 'The V3 shell consumes foundations and canonical contracts only.',
    },
  ],
}
