import type { ArchitecturePolicy } from './types'

export const currentArchitecturePolicy: ArchitecturePolicy = {
  roles: {
    '@brawltome/api': 'application',
    '@brawltome/desktop': 'application',
    '@brawltome/discord-bot': 'application',
    '@brawltome/web': 'application',
    '@brawltome/bhapi': 'adapter',
    '@brawltome/database': 'adapter',
    '@brawltome/database-migrations': 'tooling',
    '@brawltome/launch-parity': 'tooling',
    '@brawltome/game-data': 'foundation',
    '@brawltome/telemetry': 'foundation',
    '@brawltome/ui': 'foundation',
    '@brawltome/architecture': 'tooling',
    '@brawltome/accounts': 'capability',
    '@brawltome/clan': 'capability',
    '@brawltome/contracts': 'contracts',
    '@brawltome/discovery': 'capability',
    '@brawltome/identity': 'capability',
    '@brawltome/player': 'capability',
    '@brawltome/ranking': 'capability',
    '@brawltome/request-admission': 'capability',
    '@brawltome/refresh-operations': 'capability',
    '@brawltome/statistics': 'capability',
  },
  allowedExports: {
    '@brawltome/api': ['.'],
    '@brawltome/desktop': [],
    '@brawltome/discord-bot': [],
    '@brawltome/web': [],
    '@brawltome/bhapi': ['.'],
    '@brawltome/database': ['.'],
    '@brawltome/database-migrations': [],
    '@brawltome/launch-parity': [],
    '@brawltome/game-data': ['.', './legends', './reference-data'],
    '@brawltome/telemetry': ['.', './node', './propagation'],
    '@brawltome/ui': ['.'],
    '@brawltome/architecture': ['.'],
    '@brawltome/accounts': ['.', './composition'],
    '@brawltome/clan': ['.', './composition'],
    '@brawltome/contracts': ['.'],
    '@brawltome/discovery': ['.', './composition'],
    '@brawltome/identity': ['.', './composition'],
    '@brawltome/player': ['.', './composition'],
    '@brawltome/ranking': ['.', './composition'],
    '@brawltome/request-admission': ['.', './composition'],
    '@brawltome/refresh-operations': ['.', './composition'],
    '@brawltome/statistics': ['.', './composition'],
  },
  capabilityDependencies: {
    '@brawltome/accounts': [],
    '@brawltome/clan': [],
    '@brawltome/discovery': [],
    '@brawltome/identity': [],
    '@brawltome/player': [],
    '@brawltome/ranking': [],
    '@brawltome/request-admission': [],
    '@brawltome/refresh-operations': [],
    '@brawltome/statistics': [],
  },
  compositionImporters: ['@brawltome/api', '@brawltome/database-migrations'],
  contractsDependencies: ['@brawltome/game-data'],
  localImportAliases: {
    '@brawltome/desktop': ['@/'],
    '@brawltome/web': ['@/'],
  },
  workspaceRoleDependencies: {
    '@brawltome/database-migrations': ['capability'],
  },
  exceptions: [
    {
      id: 'v2-api-router-export',
      rule: 'package-export',
      importer: '@brawltome/api',
      files: ['apps/api/package.json'],
      importPath: './router',
      reason: 'V2 clients consume the API router type through an application export.',
      issue: '#186',
      expiresWhen: 'Canonical tRPC contracts no longer originate from API application source.',
    },
    {
      id: 'v2-web-api-router-client-undeclared',
      rule: 'undeclared-dependency',
      importer: '@brawltome/web',
      dependency: '@brawltome/api',
      files: ['apps/web/src/lib/trpc.ts'],
      importPath: '@brawltome/api/router',
      reason: 'The V2 web client imports its router type from the API application.',
      issue: '#186',
      expiresWhen: 'Canonical tRPC contracts no longer originate from API application source.',
    },
    {
      id: 'v2-web-api-router-client-app-import',
      rule: 'app-to-app',
      importer: '@brawltome/web',
      dependency: '@brawltome/api',
      files: ['apps/web/src/lib/trpc.ts'],
      importPath: '@brawltome/api/router',
      reason: 'The V2 web client imports its router type from the API application.',
      issue: '#186',
      expiresWhen: 'Canonical tRPC contracts no longer originate from API application source.',
    },
    {
      id: 'v2-web-api-router-server-undeclared',
      rule: 'undeclared-dependency',
      importer: '@brawltome/web',
      dependency: '@brawltome/api',
      files: ['apps/web/src/lib/trpc-server.ts'],
      importPath: '@brawltome/api/router',
      reason: 'The V2 server-side web client imports its router type from the API application.',
      issue: '#186',
      expiresWhen: 'Canonical tRPC contracts no longer originate from API application source.',
    },
    {
      id: 'v2-web-api-router-server-app-import',
      rule: 'app-to-app',
      importer: '@brawltome/web',
      dependency: '@brawltome/api',
      files: ['apps/web/src/lib/trpc-server.ts'],
      importPath: '@brawltome/api/router',
      reason: 'The V2 server-side web client imports its router type from the API application.',
      issue: '#186',
      expiresWhen: 'Canonical tRPC contracts no longer originate from API application source.',
    },
    {
      id: 'v2-discord-api-router-undeclared',
      rule: 'undeclared-dependency',
      importer: '@brawltome/discord-bot',
      dependency: '@brawltome/api',
      files: ['apps/discord-bot/src/lib/trpc.ts'],
      importPath: '@brawltome/api/router',
      reason: 'The V2 Discord client imports its router type from the API application.',
      issue: '#186',
      expiresWhen: 'Canonical tRPC contracts no longer originate from API application source.',
    },
    {
      id: 'v2-discord-api-router-app-import',
      rule: 'app-to-app',
      importer: '@brawltome/discord-bot',
      dependency: '@brawltome/api',
      files: ['apps/discord-bot/src/lib/trpc.ts'],
      importPath: '@brawltome/api/router',
      reason: 'The V2 Discord client imports its router type from the API application.',
      issue: '#186',
      expiresWhen: 'Canonical tRPC contracts no longer originate from API application source.',
    },
  ],
}
